# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97b9fc31d118eb4d4ce8ef4ca18ceb22e856e4f3f5a211b3abf733f70a49d6c54f8f9326b2cc12f99343b7c2523de52b476dfedf3c9860d9a76788ca5240d59e

test:
  secret_key_base: bffc2ca2c8f9add1fd28d9b3aa3e70cd2c7af3914e45a5f0bba5051a59f8240a4f1356b5b6361a27593006d410d47907405105990c1fb8e8dc3f84aa50263f18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
